common:
  api:
    base-url: "https://maps.googleapis.com/maps/api/geocode/json"
    api-key: ""
server:
  port: 8083
  servlet:
    contextPath: /bmg13
management:
  endpoints:
    metrics:
      enabled: true
      export:
        prometheus:
          enabled: true
    web:
      exposure:
        include: '*'